# Generated by Django 5.1.6 on 2025-10-10 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_profile_total_exchanges_profile_total_purchases_and_more'),
    ]

    operations = [
    ]
