# Generated by Django 5.1.6 on 2025-10-10 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20251010_2343'),
    ]

    operations = [
    ]
