# Generated by Django 5.1.6 on 2025-10-16 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_profile_address_profile_phone_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='phone_number',
            new_name='phone',
        ),
    ]
