# Generated by Django 5.1.6 on 2025-10-09 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sell_books', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sellbook',
            name='pdf',
        ),
    ]
