# Generated by Django 5.1.6 on 2025-10-09 13:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OfferedBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('base_price', models.PositiveIntegerField()),
                ('edition', models.PositiveIntegerField(default=1)),
                ('total_pages', models.PositiveIntegerField(default=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offered_books', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RequestedBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('base_price', models.PositiveIntegerField()),
                ('edition', models.PositiveIntegerField(default=1)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exchanges', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ExchangeRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pages_missing', models.PositiveIntegerField()),
                ('edition_difference', models.PositiveIntegerField(blank=True, null=True)),
                ('font_side_picture', models.ImageField(default='exchange_books/default.jpg', upload_to='exchange_books/')),
                ('back_side_picture', models.ImageField(default='exchange_books/default.jpg', upload_to='exchange_books/')),
                ('full_book_picture', models.ImageField(default='exchange_books/default.jpg', upload_to='exchange_books/')),
                ('author_page_picture', models.ImageField(default='exchange_books/default.jpg', upload_to='exchange_books/')),
                ('condition', models.CharField(choices=[('excellent', 'Excellent'), ('fine', 'Fine'), ('not_good', 'Not Good')], max_length=20)),
                ('calculated_price', models.PositiveIntegerField(blank=True, null=True)),
                ('final_payment', models.IntegerField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exchange_requests', to=settings.AUTH_USER_MODEL)),
                ('offered_book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exchangebook.offeredbook')),
                ('requested_book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exchangebook.requestedbook')),
            ],
        ),
    ]
