# Generated by Django 5.1.6 on 2025-09-18 10:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExchangeBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('author', models.CharField(blank=True, max_length=255)),
                ('base_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('desired_edition', models.PositiveIntegerField(default=1, help_text='Current/desired edition number')),
                ('description', models.TextField(blank=True)),
                ('allowed_accept_titles', models.TextField(blank=True, help_text='Comma-separated list of user book titles allowed (optional)')),
            ],
        ),
        migrations.CreateModel(
            name='UserExchangeRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offered_title', models.CharField(max_length=255)),
                ('offered_base_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('offered_pages_missing', models.PositiveIntegerField(default=0)),
                ('offered_edition', models.PositiveIntegerField(default=1)),
                ('offered_condition', models.CharField(choices=[('excellent', 'Excellent'), ('fine', 'Fine'), ('not_good', 'Not Good')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('computed_user_value', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('computed_final_payment', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('computed_breakdown', models.JSONField(blank=True, null=True)),
                ('requested_book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='exchangebook.exchangebook')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
