# Generated by Django 5.1.6 on 2025-09-18 11:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchangebook', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OfferedBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('base_price', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='RequestedBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('base_price', models.PositiveIntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='userexchangerequest',
            name='requested_book',
        ),
        migrations.RemoveField(
            model_name='userexchangerequest',
            name='user',
        ),
        migrations.CreateModel(
            name='ExchangeRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pages_missing', models.PositiveIntegerField(default=0)),
                ('edition_difference', models.PositiveIntegerField(default=0)),
                ('condition', models.CharField(choices=[('excellent', 'Excellent'), ('fine', 'Fine'), ('not_good', 'Not Good')], max_length=20)),
                ('calculated_price', models.PositiveIntegerField(blank=True, null=True)),
                ('final_payment', models.IntegerField(blank=True, null=True)),
                ('offered_book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exchangebook.offeredbook')),
                ('requested_book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exchangebook.requestedbook')),
            ],
        ),
        migrations.DeleteModel(
            name='ExchangeBook',
        ),
        migrations.DeleteModel(
            name='UserExchangeRequest',
        ),
    ]
