# Generated by Django 5.1.6 on 2025-10-09 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchangebook', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exchangerequest',
            old_name='font_side_picture',
            new_name='front_side_picture',
        ),
        migrations.RenameField(
            model_name='requestedbook',
            old_name='base_price',
            new_name='price',
        ),
        migrations.RemoveField(
            model_name='requestedbook',
            name='edition',
        ),
        migrations.RemoveField(
            model_name='requestedbook',
            name='user',
        ),
        migrations.AddField(
            model_name='exchangerequest',
            name='user_edition',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='requestedbook',
            name='exchangeable_amount',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='exchangerequest',
            name='calculated_price',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='exchangerequest',
            name='condition',
            field=models.CharField(choices=[('excellent', 'Excellent'), ('fine', 'Fine'), ('not_good', 'Not Good')], default='excellent', max_length=20),
        ),
        migrations.AlterField(
            model_name='exchangerequest',
            name='edition_difference',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='exchangerequest',
            name='pages_missing',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
