# Generated by Django 5.2 on 2025-10-09 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchangebook', '0002_offeredbook_requestedbook_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='exchangerequest',
            name='author_page_picture',
            field=models.ImageField(default='exchange_books/default.jpg', upload_to='exchange_books/'),
        ),
        migrations.AddField(
            model_name='exchangerequest',
            name='back_side_picture',
            field=models.ImageField(default='exchange_books/default.jpg', upload_to='exchange_books/'),
        ),
        migrations.AddField(
            model_name='exchangerequest',
            name='font_side_picture',
            field=models.ImageField(default='exchange_books/default.jpg', upload_to='exchange_books/'),
        ),
        migrations.AddField(
            model_name='exchangerequest',
            name='full_book_picture',
            field=models.ImageField(default='exchange_books/default.jpg', upload_to='exchange_books/'),
        ),
        migrations.AddField(
            model_name='offeredbook',
            name='edition',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='offeredbook',
            name='total_pages',
            field=models.PositiveIntegerField(default=100),
        ),
        migrations.AddField(
            model_name='requestedbook',
            name='edition',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='exchangerequest',
            name='edition_difference',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='exchangerequest',
            name='pages_missing',
            field=models.PositiveIntegerField(),
        ),
    ]
