# Generated by Django 5.1.6 on 2025-10-09 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchangebook', '0002_rename_font_side_picture_exchangerequest_front_side_picture_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='exchangerequest',
            name='received_amount',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
