# Generated by Django 5.1.6 on 2025-10-09 21:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exchangebook', '0003_exchangerequest_received_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exchangerequest',
            name='received_amount',
        ),
    ]
